version: "2"
networks:
  default:
    external:
      name: development-network
services:
  http:
    image: rjsandim/nginx-php-fpm-xdebugger:8.0
    container_name: nginx
    ports:
        - "80:80"
    volumes:
        - ${PROJECTS_PATH}:/var/www/html/
        - ${HTTP_CONFIG}:/etc/nginx/sites-enabled
        - ${HTTP_LOG}:/var/log/nginx/
    entrypoint: 
       - /run.sh
    depends_on:
      - mysql
      - redis
      - mongo
    environment:
      XDEBUG_REMOTE_HOST: ${XDEBUG_REMOTE_HOST}
      XDEBUG_REMOTE_PORT: ${XDEBUG_REMOTE_PORT}
  mysql:
    restart: always
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "alvo"
    volumes:
      - ${DATABASE_PATH}:/var/lib/mysql
  redis:
    restart: always
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
  mongo:
    image: mongo:3.4.1
    container_name: mongo
    ports:
      - "27017:27017"