version: "2"
networks:
  default:
    external:
      name: development
services:
  # http:
  #   image: rjsandim/nginx-php-fpm-xdebugger:8.0
  #   container_name: nginx
  #   ports:
  #       - "80:80"
  #   volumes:
  #       - ${PROJECTS_PATH}:/var/www/html/
  #       - ${HTTP_CONFIG}:/etc/nginx/sites-enabled
  #       - ${HTTP_LOG}:/var/log/nginx/
  #   entrypoint: 
  #      - /run.sh
  #   depends_on:
  #     - mysql
  #     - redis
  #     - mongo
  #   environment:
  #     XDEBUG_REMOTE_HOST: ${XDEBUG_REMOTE_HOST}
  #     XDEBUG_REMOTE_PORT: ${XDEBUG_REMOTE_PORT}
  # mysql:
  #   restart: always
  #   image: mysql:5.7
  #   container_name: mysql
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "root"
  #     MYSQL_DATABASE: "alvo"
  #   volumes:
  #     - ${DATABASE_PATH}:/var/lib/mysql
  redis:
    restart: always
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
  elasticsearch:
    image: elasticsearch:7.6.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      discovery.type: single-node
  kibana:
    image: kibana:7.6.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: "http://${ELASTIC_HOST}"
    depends_on:
      - elasticsearch
  postgres:
    restart: always
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: "root"
    volumes:
      - ${DATABASE_PATH}/postgres:/var/lib/postgresql/data
